version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: aponte_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: debug_password
      POSTGRES_DB: aponte_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
